### ISSUE TITLE
Puppet integration can run on windows

### ISSUE THREAD

**Issue by garkler** [cyberark/conjur-puppet#24]
## Link to Aha
https://cyberark.aha.io/features/AAM-85
https://cyberark.aha.io/features/AAM-86
Child of puppet 6 updates #20

## Feature Overview
Utilize the current puppet module to deliver credentials to Windows systems, so that I can easily automate Windows as well as Linux systems.

## Resources
- [High Level Feature Doc](https://cyberark365.sharepoint.com/:w:/s/Conjur/ETfLG5-p-4BIhEKMdYpqsKIBEC7r8fTb_YzBvMA_IBN2iw?e=zZntsa)
- [Detailed Feature Spec](https://github.com/conjurinc/appliance/pull/815)

### Design and Planning

- [x] Feature spec exists - parent of conjurinc/appliance#816
- [x] High-level Feature Doc for Windows Conjur Settings - parent of conjurinc/appliance#817
- [x] [SPIKE] POC for WinCred API from Ruby - parent of conjurinc/appliance#818
- [ ] Feature spec approved

### Infrastructure

- [ ] Jenkins creates on demand single use windows agents - parent of conjurinc/ops#223

### Development
- [ ] Can't add a conjur 
host with `/` - parent of #17
- [x] conjur class establishes identity for Windows servers - parent of #21
- [x] conjur::secret provides credentials for Windows servers - parent of #22

### Testing

- [x] Tests on Master Branch are broken - parent of #19
- [ ] Integration CI tests are executed in Linux and Windows environments - parent of #27 
- [ ] Unit tests exist for WinCred interface - parent of cyberark/conjur-puppet#28

### Documentation

- [x] `README` is updated

### Demo

- [ ] Demo exists for Puppet on Windows
- [ ] Video demonstration of Puppet for Windows exists

### Release

- [ ] Version is bumped
- [ ] Updated Puppet Module has been published to PuppetForge

**Comment by garkler** [comment]
@boazmichaely , @jasongarabedian , @dividedmind , @andytinkham I created an epic for the puppet for windows, I will work on adding more information to it after my conversation with Jody, please let me know what else I should add there. 
I felt that an XDD or things we do for larger features are not needed.
I added a bug fix that was asked from the field to there as well

Please review the open questions I added there too if they are relevant, Thanks !!
